AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'db/migrate/*'
  # Include:
  DisplayCopNames: true
    
Rails:
  Enabled: true

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/LineLength:
  Max: 135

Style/Documentation:
  Enabled: false

Metrics/MethodLength:
  Max: 30

Metrics/BlockLength:
  Max: 40
